### ISSUE TITLE
Not Starting with v2 Data

### ISSUE THREAD

**Issue by adamtrobbins** [PrincetonUniversity/Iseult#21]
When I try to run with Tristan v2 data in the native v2 format (/scratch/gpfs/ar3676/2b_test/output), Iseult does not start and I get the following error messages:

[21:53][ar3676@stellar-vis2 ~/scr/2b_test/output]$ iseult.py
/home/ar3676/Desktop/Iseult/src/data_loading.py:206: UserWarning: prtl/prtl.tot.00091 does not contain the dataset "u_2". Returning zero valued data.
  warnings.warn(f'{file_path} does not contain the dataset "{dataset_name}". Returning zero valued data.')
/home/ar3676/Desktop/Iseult/src/data_loading.py:206: UserWarning: prtl/prtl.tot.00091 does not contain the dataset "x_2". Returning zero valued data.
  warnings.warn(f'{file_path} does not contain the dataset "{dataset_name}". Returning zero valued data.')
/home/ar3676/Desktop/Iseult/src/data_loading.py:215: UserWarning: "gamma0" is not present in Tristan v2 datasets. Setting gamma0=1
  warnings.warn('"gamma0" is not present in Tristan v2 datasets. Setting gamma0=1')
Traceback (most recent call last):
  File "/home/ar3676/Desktop/Iseult/iseult.py", line 49, in <module>
    runMe(cmd_args)
  File "/home/ar3676/Desktop/Iseult/src/main_app.py", line 3557, in runMe
    app = MainApp('Iseult', cmd_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ar3676/Desktop/Iseult/src/main_app.py", line 1888, in __init__
    self.InitializeCanvas()
  File "/home/ar3676/Desktop/Iseult/src/main_app.py", line 2366, in InitializeCanvas
    self.ReDrawCanvas()
  File "/home/ar3676/Desktop/Iseult/src/main_app.py", line 3096, in ReDrawCanvas
    self.LoadAllKeys()
  File "/home/ar3676/Desktop/Iseult/src/main_app.py", line 2600, in LoadAllKeys
    self.DataDict[elm] = data_loading.load_dataset(filepath, elm)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ar3676/Desktop/Iseult/src/data_loading.py", line 286, in load_dataset
    if loaded_data.size == 1:
       ^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'size'

**Comment by bcaddy** [comment]
I couldn't reproduce this error with this dataset. Are you using the default view in Iseult?

**Comment by bcaddy** [comment]
On closer inspection, you're not using the version of Iseult in my PR. The instructions for getting the proper version are in PR #20, if you've already followed them then verify you're on the correct branch and run `git pull`

**Comment by adamtrobbins** [comment]
This fixed it - thanks Bob!
