### ISSUE TITLE
TotalEnergyPlot not working with Tristan v1 data

### ISSUE THREAD

**Issue by rwcmm** [PrincetonUniversity/Iseult#38]
Data directory: /scratch/gpfs/rw6831/078_periodic_test_2/output
Right clicking on a panel and selecting TotalEnergyPlot under chart type causes entire display to turn blank.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/licensed/anaconda3/2023.9/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/rw6831/Iseult/src/spectra.py", line 1078, in ctypeChanged
    self.parent.ChangePlotType(self.ctypevar.get())
  File "/home/rw6831/Iseult/src/spectra.py", line 88, in ChangePlotType
    self.FigWrap.ChangeGraph(str_arg)
  File "/home/rw6831/Iseult/src/main_app.py", line 148, in ChangeGraph
    self.parent.RenewCanvas(ForceRedraw = True)
  File "/home/rw6831/Iseult/src/main_app.py", line 2919, in RenewCanvas
    self.ReDrawCanvas(keep_view = keep_view)
  File "/home/rw6831/Iseult/src/main_app.py", line 3014, in ReDrawCanvas
    self.LoadAllKeys()
  File "/home/rw6831/Iseult/src/main_app.py", line 2562, in LoadAllKeys
    TotalElectronKE *= self.DataDict['stride'][0]*self.MainParamDict['PrtlStride'] # multiply by the stride.
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'int' object is not subscriptable
```

**Comment by bcaddy** [comment]
Should be fixed by PR #39
